### ISSUE TITLE
CRASH: ScanPrepassResources::prepare_buffers race condition

### ISSUE THREAD

**Issue by blueforesticarus** [RyanSpaker/CornGame#5]
```2024-02-20T10:08:47.945126Z  INFO bevy_winit::system: Creating new window "App" (0v1)
2024-02-20T10:08:47.945323Z  INFO log: Guessed window scale factor: 1.4166666666666667
2024-02-20T10:08:47.975637Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX Vega (RADV VEGA10)", vendor: 4098, device: 26751, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 23.3.5", backend: Vulkan }
2024-02-20T10:08:48.051108Z  INFO corn_game::app: Loading Start
2024-02-20T10:08:48.062125Z  INFO corn_game::app: Loading Finished, Elapsed Millis: 11
Max Lod: 50
thread 'Compute Task Pool (6)' panicked at src/ecs/corn/render/scan_prepass.rs:108:43:
called `Result::unwrap()` on an `Err` value: NoEntities("bevy_ecs::query::state::QueryState<&bevy_render::view::ExtractedView, bevy_ecs::query::filter::With<corn_game::ecs::main_camera::MainCamera>>")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `corn_game::ecs::corn::render::scan_prepass::ScanPrepassResources::prepare_buffers`!
thread 'Compute Task Pool (10)' panicked at /home/user/net/git/bevy/crates/bevy_render/src/pipelined_rendering.rs:49:67:
called `Result::unwrap()` on an `Err` value: RecvError```

**Comment by RyanSpaker** [comment]
Fixed, Scanprepass code will not run if no main camera is spawned.
